FROM quay.io/pypa/manylinux_2_28_x86_64
WORKDIR /opt/imagecodecs/build_utils

COPY install_nasm.sh .
RUN bash ./install_nasm.sh

COPY *patch /opt/imagecodecs/build_utils/

COPY docker_prepare_2014.sh .
RUN bash ./docker_prepare_2014.sh

RUN yum -y install cmake3

COPY download_libraries.sh .
RUN bash ./download_libraries.sh

COPY patch_dir/ patch_dir/

COPY build_libraries.sh .
RUN bash ./build_libraries.sh

FROM quay.io/pypa/manylinux2014_x86_64
WORKDIR /opt/imagecodecs/build_utils

RUN mkdir /opt/imagecodecs/build_utils/libs_build

COPY --from=0 /opt/imagecodecs/build_utils/libs_build/lib libs_build/lib
COPY --from=0 /opt/imagecodecs/build_utils/libs_build/lib64 libs_build/lib64
COPY --from=0 /opt/imagecodecs/build_utils/libs_build/include libs_build/include
COPY --from=0 /opt/imagecodecs/build_utils/libs_build/usr libs_build/usr


ENV BASE_PATH /opt/imagecodecs/
ENV BASE_LIB_PATH ${BASE_PATH}/build_utils/libs_build/
ENV LD_LIBRARY_PATH ${BASE_LIB_PATH}/lib:${BASE_LIB_PATH}/lib64:/usr/local/lib:/usr/local/lib64

ENV C_INCLUDE_PATH ${BASE_LIB_PATH}/include
ENV LIBRARY_PATH ${LD_LIBRARY_PATH}