FROM quay.io/pypa/manylinux2014_x86_64
WORKDIR /opt/imagecodecs/build_utils


COPY *patch /opt/imagecodecs/build_utils/

COPY docker_prepare_2014.sh .
RUN ./docker_prepare_2014.sh

RUN yum -y install cmake3; cp /usr/bin/cmake3 /usr/bin/cmake

COPY download_libraries.sh .
RUN ./download_libraries.sh

COPY patch_dir/ patch_dir/

COPY build_libraries.sh .
RUN ./build_libraries.sh

ENV BASE_PATH /opt/imagecodecs/
ENV BASE_LIB_PATH ${BASE_PATH}/build_utils/libs_build/
ENV LD_LIBRARY_PATH ${BASE_LIB_PATH}/lib:${BASE_LIB_PATH}/lib64:/usr/local/lib:/usr/local/lib64

ENV C_INCLUDE_PATH ${BASE_LIB_PATH}/include
ENV LIBRARY_PATH ${LD_LIBRARY_PATH}