variables:
  IMAGECODECS_CIBW: 1
  AEC_TEST_EXTENDED: 1
  BASE_PATH: $(Build.Repository.LocalPath)
  LD_LIBRARY_PATH: $(Build.Repository.LocalPath)/build_utils/libs_build/lib
  MACOSX_RPATH: $LD_LIBRARY_PATH
  # CIBW_BUILD: "cp3[8-10]*"

stages:
  - stage: GetLibsSrc
    jobs:
      - job: linux
        pool: { vmImage: "Ubuntu-22.04" }
        steps:
          - bash: bash build_utils/download_libraries.sh
            displayName: "Download libraries"
          - bash: tar czf libraries.tgz build_utils/libs_src
            displayName: "Create archive"
          - publish: libraries.tgz
            artifact: LibsSrc_tar
  - stage: BuildLinux
    dependsOn: [GetLibsSrc]
    jobs:
      - job: linux_test_build
        pool: { vmImage: "Ubuntu-22.04" }
        variables:
          IMCD_SKIP_JPEG12: 1
        steps:
          - checkout: self
            submodules: true
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.8"
            displayName: "Use Python 3.8"

          - bash: |
              sudo apt-get -y update
              sudo apt-get -y install nasm autopoint libsnappy-dev meson nasm ninja-build
            displayName: "install build tools"

          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: LibsSrc_tar
              path: $(Build.SourcesDirectory)

          - bash: tar -xf libraries.tgz
            displayName: "Unpack"

          - bash: bash build_utils/build_libraries.sh
            displayName: "build libraries"

          - script: |
              python -m pip install --upgrade pip
              python -m pip install numpy cython wheel
            displayName: "Install dependencies"

          - bash: pip install -r requirements_azure.txt
            displayName: "install test dependencies"

          - script: pip install -e imagecodecs_src
            displayName: "install package"

          - script: pytest imagecodecs_src/tests --timeout=300
            displayName: "run test"
  - stage: BuildMacos
    dependsOn: [GetLibsSrc]
    jobs:
      - job: macos_test_build
        pool: { vmImage: "macos-11" }
        timeoutInMinutes: 100
        variables:
          LIBRARY_PATH: $(LD_LIBRARY_PATH)
          LD_RUNPATH_SEARCH_PATH: $(LD_LIBRARY_PATH)
          DYLD_FALLBACK_LIBRARY_PATH: $(LD_LIBRARY_PATH)
          SKIP_OMP: 1
          IMCD_SKIP_JPEG12: 1
          CC: clang
          CXX: clang++
        steps:
          - checkout: self
            submodules: true
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.8"
            displayName: "Use Python 3.8"

          - bash: brew install pcre openssl nasm automake libtool snappy ninja meson cmake
            displayName: "install build tools"

          # - bash: bash build_utils/build_libomp.sh
          #   displayName: "build and install libomp"

          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: LibsSrc_tar
              path: $(Build.SourcesDirectory)

          - bash: tar -xf libraries.tgz
            displayName: "Unpack"

          - bash: |
              bash build_utils/build_libraries.sh
            displayName: "build libraries"

          - bash: bash build_utils/fix_macos_lib.sh
            displayName: "Fix libraries load path"

          - bash: ls build_utils/libs_build/lib/*
            displayName: "show install result"

          - script: |
              python -m pip install --upgrade pip
              python -m pip install numpy cython wheel
            displayName: "Install dependencies"

          - bash: pip install -e ./imagecodecs_src
            displayName: "Install project"

          #- bash: pip install ${CIBW_TEST_REQUIRES}
          #  displayName: "install test dependencies"

          #- script: pytest imagecodecs_src/tests --timeout=300
          #  displayName: "run test"

      - job: macos_wheel
        pool: { vmImage: "macos-11" }
        timeoutInMinutes: 150
        variables:
          LIBRARY_PATH: $(LD_LIBRARY_PATH)
          DYLD_LIBRARY_PATH: $(LD_LIBRARY_PATH)
          LD_RUNPATH_SEARCH_PATH: $(LD_LIBRARY_PATH)
          DYLD_FALLBACK_LIBRARY_PATH: $(LD_LIBRARY_PATH)
          MACOSX_DEPLOYMENT_TARGET: "10.9"
          SKIP_OMP: 1
          IMCD_SKIP_JPEG12: 1
          CC: clang
          CXX: clang++
        steps:
          - checkout: self
            submodules: true
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.8"
            displayName: "Use Python 3.8"

          - bash: brew install pcre openssl nasm automake libtool pkg-config snappy ninja meson cmake
            displayName: "install build tools"

          # - bash: bash build_utils/build_libomp.sh
          #   displayName: "build and install libomp"

          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: LibsSrc_tar
              path: $(Build.SourcesDirectory)

          - bash: tar -xf libraries.tgz
            displayName: "Unpack"

          - bash: |
              bash build_utils/build_libraries.sh
            displayName: "build libraries"

          - bash: bash build_utils/fix_macos_lib.sh
            displayName: "Fix libraries load path"

          - script: |
              python -m pip install --upgrade pip
              python -m pip install numpy cython
              python -m pip install cibuildwheel
            displayName: "Install dependencies"

          - script: cibuildwheel ./imagecodecs_src
            displayName: "cibuildwheel"

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: wheelhouse
              artifactName: wheels

  - stage: BuildManylinux
    dependsOn: []
    jobs:
      - job: linux_wheel
        timeoutInMinutes: 150
        strategy:
          matrix:
            manylinux2014_x86_64:
              CIBW_SKIP: "*686  pp37* cp37* *-musllinux_x86_64"
            manylinux2014_i686:
              CIBW_SKIP: "*64 pp* cp37* cp310* *-musllinux_i686"
        pool: { vmImage: "Ubuntu-20.04" }
        steps:
          - checkout: self
            submodules: true
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.8"
            displayName: "Use Python 3.8"

          - script: |
              python -m pip install --upgrade pip
              python -m pip install numpy cython
              python -m pip install cibuildwheel
            displayName: "Install dependencies"

          - script: cibuildwheel ./imagecodecs_src
            displayName: "cibuildwheel"

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: wheelhouse
              artifactName: wheels
