version: 2


jobs:
  manylinux2014-aarch64:
    machine:
      image: ubuntu-2004:2022.04.1
    resource_class: arm.medium
    environment:
      CIBW_MANYLINUX_AARCH64_IMAGE: odidev/imagecodecs_manylinux2014_aarch64:2021.10.05
      BASE_PATH: ~/
      LD_LIBRARY_PATH=: ~/build_utils/libs_build/lib
      AEC_TEST_EXTENDED: 1
      PYTHON: python3
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Install dependencies
          command: |
            pip3 install cibuildwheel
      - run:
          name: cibuildwheel
          command: |
            python -m cibuildwheel ./imagecodecs_src --output-dir wheelhouse --config-file pyproject.toml

      - store_artifacts:
          path: ./wheelhouse
          destination: artifacts

workflows:
  version: 2
  main:
    jobs:
      - manylinux2014-aarch64
